### ISSUE TITLE
Issue to build hydra-dynamo

### ISSUE THREAD

**Issue by michaldengusiak** [HydraShare/hydra-dynamo#18] opened 2020-04-07 10:24 UTC
Hi,

I have an error when trying to build. See Below...
I am using:
-Microsoft Visual Studio 2019
-Microsoft .NET Framework 4.7.2
any help will be appreciated

![image](https://user-images.githubusercontent.com/26113670/78658286-e5f0b480-78c1-11ea-83a7-04ce902e07c0.png)

![image](https://user-images.githubusercontent.com/26113670/78658662-5a2b5800-78c2-11ea-8772-c0f468219922.png)

**Comment by michaldengusiak** [comment] 2020-04-07 16:21
@alfarok 

I manage to solve it by adding manually  and builds now
![image](https://user-images.githubusercontent.com/26113670/78691858-084df680-78f1-11ea-9f86-6b2c6115c25d.png)

However, I have right  now problem that it freezes on Dynamo, without even running anything
I am using Revit 2020.2 and Dynamo 2.3.0.

do you have some time to help me?
![image](https://user-images.githubusercontent.com/26113670/78694105-15b8b000-78f4-11ea-840d-8863122a3548.png)

![image](https://user-images.githubusercontent.com/26113670/78694819-23226a00-78f5-11ea-8087-52c2ce44a186.png)

**Comment by alfarok** [comment] 2020-04-07 21:46
Hey @michaldengusiak, glad you were able to figure out the SDK registry issue.  I have seen that before and think it's related to a change in SDK locations between version but seems like a installation [bug](https://developercommunity.visualstudio.com/content/problem/18560/can-not-find-resgenexe-in-task.html) on Microsofts part since it still looks for the old path.  The `resgen.exe` dependency is only for embedding the icons for the package.

In regards to the freezing you are seeing above, I have been unable to reproduce in Revit 2020.2 and Dynamo 2.3.0.  At first I thought it may be because the package was built against the Dynamo 2.0 Beta NuGet packages (thinking there was an API breaking change in the release NuGets), but it executed as expected on my machine.

How are you referencing the package once you have rebuilt?  
You should copy the `Hydra` folder from `C:\YOUR_REPO_ROOT\hydra-dynamo\dynamo_package` to `C:\Users\YOUR_USERNAME\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages`, or add a postbuild step to the project to do so automatically.  I wouldn't try and load it from `File -> Import Library` and load the .dll directly since the package has dependencies from 2 project files with different bin folders that get copied appropriately into the `Hydra` folder.

To debug locally you can also start Revit and attach it as a process in Visual Studio under `Debug -> Attach to Process`, select `Revit.exe` from the list, and hit `Attach`.  From this point try adding the node to the canvas in Dynamo and any errors should be hit and shown in the code in Visual Studio.

One other option is to try installing from the package manager to confirm if it is an issue with the package or your local build.

Hope this helps and let me know if you are able to get it resolved.  Glad to see there is still some interest in this project.  I stopped updating it a while back because it didn't seem to be getting as much traction as the the grasshopper component.  

Cheers!

**Comment by michaldengusiak** [comment] 2020-04-08 07:50
@alfarok thanks a lot for your help. Of course we are interested in Dynamo version :) GH is working well now. So we follow these steps but still freezing. 

Can you send me your .zip with Dynamo Hydra package to see if this will work on my PC.  We trying to debug but after few second it seems to freeze Revit and Dynamo. I have tried to run it in Debug mode and it gets me to HydraNodeModel.Version property where it loses track. 
Maybe I am referencing the wrong version, can you also send your print screen with registry information under Windows to see what is your reference?

**Comment by michaldengusiak** [comment] 2020-04-08 11:18
@alfarok great news,
All sorted now, we manage to fork and test on 2 laptops and is working fine, we added some code for automatic git operations to our fork,

the only question is how I could modify code to allow connect node for tags or some other inputs to `HydraButtonControl.xaml`

**Comment by alfarok** [comment] 2020-04-08 16:19
@michaldengusiak that's awesome!  Glad you got it working.

Are you trying to add inputs to the node itself or just add additional fields to the node UI?

If you want to add input ports, check out this [earlier version](https://github.com/HydraShare/hydra-dynamo/commit/92c75ca1f608778ff64521acdeee7403bf640ae9?short_path=f83e13e#diff-f83e13e0b5b186931683f21619ed1228) which is more similar to the grasshopper component.  If this is more of what you are going for you should be able to roll back the git history with some additional changes to make the node operate in more recent Dynamo releases.

If the later, you can add additional UI fields [here](https://github.com/HydraShare/hydra-dynamo/blob/master/src/HydraDynamo/Controls/HydraButtonControl.xaml#L26) and read those values off the UI [here](https://github.com/HydraShare/hydra-dynamo/blob/master/src/HydraDynamo/NodeModels/HydraNodeModel.cs#L56).  Overall this pattern could use some cleanup but should be enough to accomplish what you are hoping to do.

For more general info on working with Custom UI nodes in Dynamo I would check out these [sample files](https://github.com/DynamoDS/DynamoSamples/tree/master/src/SampleLibraryUI) or another project I worked on, [NodeModelCharts](https://github.com/alfarok/NodeModelCharts), which is a bit more up-to-date and abides by better standards.

I am closing this issue for now since the node seems to be working as expected but feel free to open up additional issues as they arise or make pull requests with any changes you feel others may benefit from!

**Closed as completed by alfarok** 2020-04-08 16:19 UTC
